### ISSUE TITLE
Bug report : Issue with 16-bit call instruction.

### ISSUE THREAD

**Issue by mylifeisabug** [Recoskie/X86-64-Disassembler-JS#5]
I raised this [bug](https://github.com/gchq/CyberChef/issues/246) over on the CyberChef issues page, and the devs over there pointed me here. 

Basically, in 16-bit code, an intra-segment direct CALL (opcode starting with 0xE8) should only be three bytes long and take a single 16-bit displacement like so: 0xE8, disp-low, disp-high

But, the two bytes following the `CALL` are also grouped in with the opcode, which would be correct only in 32-bit code.

Here's a disassembly of a raw hex file containing the bytes `E8 00 00 90 90` using ndisasm.exe with the CPU Mode set to 16-bit:

![call16](https://user-images.githubusercontent.com/36830529/36691197-144e8384-1afa-11e8-827a-68d4c2d1d0de.png)

And here's a disassembly of the same file with the CPU mode set to 32-bit:

![call32](https://user-images.githubusercontent.com/36830529/36691255-477ee802-1afa-11e8-91d4-90fe57dbf9cc.png)

Neither of these are output by your x86 disassembler, in this case it outputs `CALL 0005` and no `NOP` instructions which isn't correct. This form of `CALL` shouldn't be five bytes long in 16-bit code, it should be three bytes long instead.

**Comment by Recoskie** [comment]
Thanks for noticing the Call instruction 0xE8, and Jump instruction 0xE9 did not adjust displacement size to the set bit mode. The two instructions had been fixed.
