### ISSUE TITLE
Wrong calculating jump adresses

### ISSUE THREAD

**Issue by FeelUsM** [Recoskie/X86-64-Disassembler-JS#6]
I try to compare result of your disassemler and https://onlinedisassembler.com/odaweb/strcpy_x86
and in this example (strcpy_x86) at address 000000001d I see wrong address for jne command
ODA: jne 00000010 (loop lable at address 00000010)
your: jne 00000110 (if EIP=00000000)

**Comment by Recoskie** [comment]
Hey thanks for finding this bug. It seems the sing bit was carried outside the address. The relative address should come out to the proper address location now.

**Comment by Recoskie** [comment]
Hey thanks for finding this bug. It seems the sing bit was carried outside the address. The relative address should come out to the proper address location now.
