### ISSUE TITLE
16-bit register source for MOVSX

### ISSUE THREAD

**Issue by nepx** [Recoskie/X86-64-Disassembler-JS#8]
Hi, 

Opcode 0F BF (MOVSX) should have a 16-bit register as a source operand, but it currently displays as a 32-bit register. 

- <code>4D0FBFE4                        MOVSX R12,<b>R12D</b></code> (should be R12W)
- <code>450FBFE4                        MOVSX R12D,<b>R12D</b></code> (should be R12W)
- <code>0FBFE4                          MOVSX ESP,<b>ESP</b></code> (should be SP)

**Comment by Recoskie** [comment]
MOVSX is now fixed. Thank you for reporting the issue.
