### ISSUE TITLE
REX.R is sometimes used instead of REX.B

### ISSUE THREAD

**Issue by nepx** [Recoskie/X86-64-Disassembler-JS#9]
For certain opcodes (`push`, `pop`, `mov imm`), REX.R is used instead of REX.B. 

<pre>
0000000000000000 4150                            PUSH RAX
0000000000000002 4450                            PUSH R8
0000000000000004 4158                            POP RAX
0000000000000006 4458                            POP R8
0000000000000008 41B000                          MOV AL,00
000000000000000B 44B000                          MOV R8B,00
000000000000000E 41B400                          MOV SPL,00
0000000000000011 44B400                          MOV R12B,00
0000000000000014 41B800000000                    MOV EAX,00000000
000000000000001A 44B800000000                    MOV R8D,00000000

</pre>

Output from objdump: 

```
0:  41 50                   push   r8
2:  44 50                   rex.R push rax
4:  41 58                   pop    r8
6:  44 58                   rex.R pop rax
8:  41 b0 00                mov    r8b,0x0
b:  44 b0 00                rex.R mov al,0x0
e:  41 b4 00                mov    r12b,0x0
11: 44 b4 00                rex.R mov spl,0x0
14: 41 b8 00 00 00 00       mov    r8d,0x0
1a: 44 b8 00 00 00 00       rex.R mov eax,0x0 
```

This occurs mainly for those opcodes that don't have ModR/M bytes.

**Comment by Recoskie** [comment]
The REX.R and REX.B mixup is now fixed. Thank you for reporting the issue and helping out.
